on:
  schedule:
    - cron: '55 * * * *'
    
jobs:
  create_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
